# Pandas Basics
Pandas provides `Series` (1D) and `DataFrame` (2D) structures for handling tabular data efficiently.

## 1. Series

In [15]:
import pandas as pd

s = pd.Series([10, 20, 30, 40], index=["a", "b", "c", "d"])
print(s)
print(s["b"])
print(s.values)
print(s.index)

a    10
b    20
c    30
d    40
dtype: int64
20
[10 20 30 40]
Index(['a', 'b', 'c', 'd'], dtype='object')

## 2. DataFrame Creation

In [16]:
data = {
    "Name": ["Yugal", "Aashma", "Rita", "Sam"],
    "Age": [25, 22, 28, 30],
    "Score": [85, 90, 78, 88]
}

df = pd.DataFrame(data)
df

     Name  Age  Score
0   Yugal   25     85
1  Aashma   22     90
2    Rita   28     78
3     Sam   30     88

## 3. Inspecting Data

In [17]:
print(df.shape)
print(df.columns)
print(df.dtypes)
df.info()
df.describe()

(4, 3)
Index(['Name', 'Age', 'Score'], dtype='object')
Name     object
Age       int64
Score     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

         Age      Score
count   4.00   4.000000
mean   26.25  85.250000
std     3.50   5.251984
min    22.00  78.000000
25%    24.25  83.250000
50%    26.50  86.500000
75%    28.50  88.500000
max    30.00  90.000000

## 4. Selecting Data (loc / iloc)

In [18]:
print(df["Name"])            # single column
print("\n")
print(df[["Name", "Age"]])   # multiple columns
print("\n")
print(df.loc[0])              # row by label
print("\n")
print(df.iloc[1])             # row by position
print("\n")
print(df.loc[df["Age"] > 25]) # conditional filtering

0     Yugal
1    Aashma
2      Rita
3       Sam
Name: Name, dtype: object


     Name  Age
0   Yugal   25
1  Aashma   22
2    Rita   28
3     Sam   30


Name     Yugal
Age         25
Score       85
Name: 0, dtype: object


Name     Aashma
Age          22
Score        90
Name: 1, dtype: object


   Name  Age  Score
2  Rita   28     78
3   Sam   30     88

## 5. Adding / Modifying Columns

In [19]:
df["Passed"] = df["Score"] >= 80
df["Age_in_5_years"] = df["Age"] + 5
df

     Name  Age  Score  Passed  Age_in_5_years
0   Yugal   25     85    True              30
1  Aashma   22     90    True              27
2    Rita   28     78   False              33
3     Sam   30     88    True              35

## 6. Sorting and Grouping

In [20]:
print(df.sort_values("Score", ascending=False))

grouped = df.groupby("Passed")["Score"].mean()
print(grouped)

     Name  Age  Score  Passed  Age_in_5_years
1  Aashma   22     90    True              27
3     Sam   30     88    True              35
0   Yugal   25     85    True              30
2    Rita   28     78   False              33
Passed
False    78.000000
True     87.666667
Name: Score, dtype: float64

## 7. Handling Missing Data

In [21]:
import numpy as np

df_missing = df.copy()
df_missing.loc[1, "Score"] = np.nan

print(df_missing.isnull().sum())
print(df_missing.fillna(df_missing["Score"].mean()))
print(df_missing.dropna())

Name              0
Age               0
Score             1
Passed            0
Age_in_5_years    0
dtype: int64
     Name  Age      Score  Passed  Age_in_5_years
0   Yugal   25  85.000000    True              30
1  Aashma   22  83.666667    True              27
2    Rita   28  78.000000   False              33
3     Sam   30  88.000000    True              35
    Name  Age  Score  Passed  Age_in_5_years
0  Yugal   25   85.0    True              30
2   Rita   28   78.0   False              33
3    Sam   30   88.0    True              35

## Summary
Pandas builds on NumPy to provide labeled, tabular data structures ideal for cleaning, exploring, and transforming datasets before feeding them into ML models.